
x-common-variables:
  &common-variables
  MYSQL_USER: music
  MYSQL_PASSWORD: music
  MYSQL_DATABASE: music_program
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      # if you have mysql running on localhost you may need
      # to use a different port number for mysql_container
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  server:
    build: ./server
    container_name: server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start

  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
